import { Poppins, Chicle } from "next/font/google";
import "./globals.css";
import Background from "@/components/all_pages/background";
import ReactQueryProvider from "@/util/reactQuery";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const chicle = Chicle({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-chicle",
});

export const metadata = {
  title: "Taki's Adventures a Pawsome Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`relative bg-takiBrown-300 ${poppins.variable} ${chicle.variable} ${poppins.className}`}
      >
        <div id="modal-root"></div>
        <Background />
        <ReactQueryProvider> {children}</ReactQueryProvider>
      </body>
    </html>
  );
}
